version: '3.8'

services:
  libre-webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:5173'
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3001
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      # For network access, add your IP/hostname to CORS_ORIGIN:
      - CORS_ORIGIN=http://localhost:8080
      - SINGLE_USER_MODE=false
      # JWT_SECRET: Generate with 'openssl rand -hex 64' and set via .env file or environment
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - FRONTEND_PORT=5173
      # Timeout configuration for large models on multiple GPUs
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-300000}
      - OLLAMA_LONG_OPERATION_TIMEOUT=${OLLAMA_LONG_OPERATION_TIMEOUT:-900000}
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-300000}
      # Database path - points to the volume mount
      - DATA_DIR=/app/backend/data
    volumes:
      - libre_webui_data:/app/backend/data
      - libre_webui_temp:/app/backend/temp
    restart: unless-stopped
    networks:
      - libre-webui-network

volumes:
  libre_webui_data:
  libre_webui_temp:

networks:
  libre-webui-network:
    driver: bridge
